name: rick_and_morty
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.0
  injectable: ^2.3.0
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.2
  url_launcher: ^6.1.12
  device_preview: ^1.1.0
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  go_router: ^10.1.1
  mocktail: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6
  bloc_test: ^9.1.4

flutter:

  uses-material-design: true


